#!/usr/bin/env bash

# Rsync memories from backup1 to backup2
source="/Volumes/backup1/memories/"
destination="baobei:/volume1/backup2/memories/"

# Validate source and destination exists
if [ ! -d "$source" ]; then
  echo "Source does not exist: $source"
  exit 1
fi

# Rsync
cat << EOF
Rsync memories from:

     Source: $source
Destination: $destination

EOF
rsync -av --delete \
  --exclude='*@SynoEAStream' --exclude='@eaDir/' \
  "$source" "$destination" "$@"