#!/usr/bin/env bash

cat <<EOF
Your GOPROXY Personal Access Token (PAT) has expired?

- Renew it https://github.com/settings/tokens/1471022409
- Paste it in your ~/.netrc file
- Re-enable SSO for the GitHub org

More info: https://github.com/github/goproxy/blob/main/doc/user.md 😉
EOF
